# Generated by Django 6.0 on 2025-12-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B3Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dias_corridos', models.IntegerField(help_text='Dias corridos')),
                ('di_pre_252', models.DecimalField(decimal_places=6, help_text='DI x PRE 252', max_digits=12)),
                ('di_pre_360', models.DecimalField(decimal_places=6, help_text='DI x PRE 360', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'dias_corridos'],
                'unique_together': {('date', 'dias_corridos')},
            },
        ),
    ]
