# Generated by Django 6.0 on 2025-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date associated with this estimation attempt')),
                ('beta0_initial', models.DecimalField(decimal_places=8, help_text='Initial β0', max_digits=15)),
                ('beta1_initial', models.DecimalField(decimal_places=8, help_text='Initial β1', max_digits=15)),
                ('beta2_initial', models.DecimalField(decimal_places=8, help_text='Initial β2', max_digits=15)),
                ('beta3_initial', models.DecimalField(decimal_places=8, help_text='Initial β3', max_digits=15)),
                ('lambda1_initial', models.DecimalField(decimal_places=8, help_text='Initial λ1', max_digits=15)),
                ('lambda2_initial', models.DecimalField(decimal_places=8, help_text='Initial λ2', max_digits=15)),
                ('beta0_final', models.DecimalField(decimal_places=8, help_text='Final β0', max_digits=15)),
                ('beta1_final', models.DecimalField(decimal_places=8, help_text='Final β1', max_digits=15)),
                ('beta2_final', models.DecimalField(decimal_places=8, help_text='Final β2', max_digits=15)),
                ('beta3_final', models.DecimalField(decimal_places=8, help_text='Final β3', max_digits=15)),
                ('lambda1_final', models.DecimalField(decimal_places=8, help_text='Final λ1', max_digits=15)),
                ('lambda2_final', models.DecimalField(decimal_places=8, help_text='Final λ2', max_digits=15)),
                ('observation', models.TextField(blank=True, help_text='Notes about this estimation attempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linear Attempt',
                'verbose_name_plural': 'Linear Attempts',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
