# Generated by Django 6.0 on 2025-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearattempt',
            name='beta0_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final β0', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta1_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final β1', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta2_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final β2', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta3_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final β3', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda1_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final λ1', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda2_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Final λ2', max_digits=15, null=True),
        ),
    ]
