# Generated by Django 6.0 on 2025-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0002_alter_linearattempt_beta0_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Holiday date', unique=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['date'],
            },
        ),
    ]
