# Generated by Django 6.0 on 2025-12-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0003_feriados'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearattempt',
            name='rmse_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='RMSE for final parameters', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='linearattempt',
            name='rmse_initial',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='RMSE for initial parameters', max_digits=15, null=True),
        ),
    ]
