# Generated by Django 6.0 on 2025-12-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0004_linearattempt_rmse_final_linearattempt_rmse_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearattempt',
            name='mae_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='MAE for final parameters', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='linearattempt',
            name='mae_initial',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='MAE for initial parameters', max_digits=15, null=True),
        ),
    ]
