# Generated by Django 6.0 on 2025-12-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0005_linearattempt_mae_final_linearattempt_mae_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearattempt',
            name='r2_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='R² for final parameters', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='linearattempt',
            name='r2_initial',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='R² for initial parameters', max_digits=15, null=True),
        ),
    ]
