# Generated by Django 6.0 on 2025-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0006_linearattempt_r2_final_linearattempt_r2_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearattempt',
            name='objective_function_final',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Objective Function for final parameters', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='linearattempt',
            name='objective_function_initial',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Objective Function for initial parameters', max_digits=15, null=True),
        ),
    ]
