# Generated by Django 6.0 on 2025-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0008_alter_linearattempt_beta0_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearattempt',
            name='beta0_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final β0', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta0_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial β0', max_digits=18),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta1_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final β1', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta1_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial β1', max_digits=18),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta2_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final β2', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta2_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial β2', max_digits=18),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta3_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final β3', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='beta3_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial β3', max_digits=18),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda1_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final λ1', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda1_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial λ1', max_digits=18),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda2_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final λ2', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='lambda2_initial',
            field=models.DecimalField(decimal_places=15, help_text='Initial λ2', max_digits=18),
        ),
    ]
