# Generated by Django 6.0 on 2025-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svensson_estimates', '0009_alter_linearattempt_beta0_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearattempt',
            name='objective_function_final',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Objective Function for final parameters', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='linearattempt',
            name='objective_function_initial',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Objective Function for initial parameters', max_digits=18, null=True),
        ),
    ]
